---
driver:
  name: vagrant
provisioner:
  name: chef_solo
  always_update_cookbooks: true
verifier:
  name: inspec
platforms:
  - name: ubuntu-17.10
suites:
  - name: default
    run_list:
      - recipe[wpmanager::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
          wp:
            sites:
              - siriannitest.duckdns.org
              - siriannitest1.duckdns.org
            mysql:
              password: "securepassword"
